language: python
sudo: false

matrix:
  include:
    - python: "2.7"
      env: DEPS="nomkl numpy=1.9*" DEPSSM="tifffile" BUILD_DOCS=false
    - python: "2.7"
      env: DEPS="nomkl numpy=1.9* scipy pillow matplotlib scikit-image jinja2" DEPSSM="pyav tifffile" BUILD_DOCS=false
    - python: "3.4"
      env: DEPS="numpy=1.9*" DEPSSM="tifffile" BUILD_DOCS=false
    - python: "3.4"
      env: DEPS="numpy=1.9* scipy pillow matplotlib scikit-image jinja2 ipython sphinx sphinx_rtd_theme numpydoc" DEPSSM="pyav tifffile" BUILD_DOCS=true

install:
  - conda update --yes conda
  - conda create -n testenv --yes $DEPS nose pip python=$TRAVIS_PYTHON_VERSION
  - conda install -n testenv -c soft-matter --yes $DEPSSM
  - source activate testenv
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then pip install libtiff; fi
  - pip install slicerator jpype1
  - python setup.py build_ext install


before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ];
    then
        wget http://repo.continuum.io/miniconda/Miniconda-3.7.3-Linux-x86_64.sh -O miniconda.sh;
    else
        wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

script:
    - nosetests --nologcapture
    # Doc Build needs: pillow matplotlib ipython sphinx sphinx_rtd_theme numpydoc
    - if [ $BUILD_DOCS == true ]; then make html --directory=./doc; fi

after_success:
    - cd $TRAVIS_BUILD_DIR
    - |
      if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == 'soft-matter/pims' && $BUILD_DOCS == true && $TRAVIS_BRANCH == 'master' ]]; then
        echo "Uploading documentation"
        openssl aes-256-cbc -K $encrypted_63b17445501f_key -iv $encrypted_63b17445501f_iv -in soft-matter-docs-deploy.enc -out soft-matter-docs-deploy -d
        eval `ssh-agent -s`
        chmod 600 soft-matter-docs-deploy
        ssh-add soft-matter-docs-deploy
        git config --global user.email "Travis@nomail"
        git config --global user.name "Travis"
        git config --global push.default simple
        git clone git@github.com:soft-matter/soft-matter.github.io.git ./doc-repo
        cd doc-repo/pims
        git checkout --orphan temp_branch
        git rm -rf ./dev
        mv $TRAVIS_BUILD_DIR/doc/build/html ./dev
        if [ -n "$TRAVIS_TAG" ]; then
          cp -R dev $TRAVIS_TAG;
        fi
        git add -A
        git commit -m "Docs build of pims commit $TRAVIS_COMMIT"
        git branch -D master
        git branch -m master
        git push --set-upstream origin master --force
      fi
