language: python
python:
  - 2.7
  - 3.3

virtualenv:
  system_site_packages: true

before_install:
  - ci/before_install.sh

install:
  - pip install -e svn+http://pylibtiff.googlecode.com/svn/trunk/
  - python setup.py build_ext install

script: nosetests -a '!slow'
