language: python

python:
  - 2.7
  - 3.4

install:
  - conda update --yes conda
  - conda create -n testenv --yes numpy scipy nose pillow matplotlib scikit-image jinja2 pip python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then pip install libtiff jpype1; fi
  - export LD_LIBRARY_PATH=/usr/local/lib LIBRARY=ffmpeg;
  - wget https://raw.githubusercontent.com/mikeboers/PyAV/master/scripts/test-setup;
  - bash ./test-setup;
  - pip install av;
  - python setup.py build_ext install


before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; 
    then 
        wget http://repo.continuum.io/miniconda/Miniconda-3.7.3-Linux-x86_64.sh -O miniconda.sh; 
    else 
        wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh; 
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

script: nosetests --nologcapture
