language: python
python:
  - 2.7
  - 3.3

install:
  - sudo apt-get update
  - sudo apt-get install libatlas-base-dev liblapack-dev
  - sudo apt-get build-dep python-numpy python-scipy python-nose python-matplotlib
  - pip install six numpy scipy nose matplotlib
  - pip install -e svn+http://pylibtiff.googlecode.com/svn/trunk/
  - python setup.py build_ext install

script: nosetests -a '!slow'
